# Generated by Django 3.0.4 on 2021-04-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='hours',
            new_name='hours_done',
        ),
        migrations.AddField(
            model_name='account',
            name='hours_left',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
