# Generated by Django 3.0.4 on 2021-04-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210416_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='instructor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='instructor',
            field=models.ManyToManyField(related_name='instructor', to='api.Account'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='student',
        ),
        migrations.AddField(
            model_name='appointment',
            name='student',
            field=models.ManyToManyField(related_name='student', to='api.Account'),
        ),
    ]
